// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rvanmech/unky-mo/internal/ops (interfaces: TmuxClient,ClaudeReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_deps.go -package=mock_ops github.com/rvanmech/unky-mo/internal/ops TmuxClient,ClaudeReader
//

// Package mock_ops is a generated GoMock package.
package mock_ops

import (
	reflect "reflect"

	claude "github.com/rvanmech/unky-mo/internal/claude"
	tmux "github.com/rvanmech/unky-mo/internal/tmux"
	gomock "go.uber.org/mock/gomock"
)

// MockTmuxClient is a mock of TmuxClient interface.
type MockTmuxClient struct {
	ctrl     *gomock.Controller
	recorder *MockTmuxClientMockRecorder
	isgomock struct{}
}

// MockTmuxClientMockRecorder is the mock recorder for MockTmuxClient.
type MockTmuxClientMockRecorder struct {
	mock *MockTmuxClient
}

// NewMockTmuxClient creates a new mock instance.
func NewMockTmuxClient(ctrl *gomock.Controller) *MockTmuxClient {
	mock := &MockTmuxClient{ctrl: ctrl}
	mock.recorder = &MockTmuxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTmuxClient) EXPECT() *MockTmuxClientMockRecorder {
	return m.recorder
}

// CreateWindow mocks base method.
func (m *MockTmuxClient) CreateWindow(name, cwd string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWindow", name, cwd)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWindow indicates an expected call of CreateWindow.
func (mr *MockTmuxClientMockRecorder) CreateWindow(name, cwd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWindow", reflect.TypeOf((*MockTmuxClient)(nil).CreateWindow), name, cwd)
}

// DetachClient mocks base method.
func (m *MockTmuxClient) DetachClient() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachClient")
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachClient indicates an expected call of DetachClient.
func (mr *MockTmuxClientMockRecorder) DetachClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachClient", reflect.TypeOf((*MockTmuxClient)(nil).DetachClient))
}

// KillPane mocks base method.
func (m *MockTmuxClient) KillPane(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillPane", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillPane indicates an expected call of KillPane.
func (mr *MockTmuxClientMockRecorder) KillPane(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillPane", reflect.TypeOf((*MockTmuxClient)(nil).KillPane), paneID)
}

// KillSession mocks base method.
func (m *MockTmuxClient) KillSession(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillSession", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillSession indicates an expected call of KillSession.
func (mr *MockTmuxClientMockRecorder) KillSession(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillSession", reflect.TypeOf((*MockTmuxClient)(nil).KillSession), name)
}

// KillWindow mocks base method.
func (m *MockTmuxClient) KillWindow(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillWindow", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillWindow indicates an expected call of KillWindow.
func (mr *MockTmuxClientMockRecorder) KillWindow(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillWindow", reflect.TypeOf((*MockTmuxClient)(nil).KillWindow), target)
}

// ListSessions mocks base method.
func (m *MockTmuxClient) ListSessions() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockTmuxClientMockRecorder) ListSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockTmuxClient)(nil).ListSessions))
}

// ListWindowPanes mocks base method.
func (m *MockTmuxClient) ListWindowPanes(target string) ([]tmux.PaneInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWindowPanes", target)
	ret0, _ := ret[0].([]tmux.PaneInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWindowPanes indicates an expected call of ListWindowPanes.
func (mr *MockTmuxClientMockRecorder) ListWindowPanes(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWindowPanes", reflect.TypeOf((*MockTmuxClient)(nil).ListWindowPanes), target)
}

// ListWindows mocks base method.
func (m *MockTmuxClient) ListWindows() ([]tmux.Window, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWindows")
	ret0, _ := ret[0].([]tmux.Window)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWindows indicates an expected call of ListWindows.
func (mr *MockTmuxClientMockRecorder) ListWindows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWindows", reflect.TypeOf((*MockTmuxClient)(nil).ListWindows))
}

// PaneID mocks base method.
func (m *MockTmuxClient) PaneID(target string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaneID", target)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaneID indicates an expected call of PaneID.
func (mr *MockTmuxClientMockRecorder) PaneID(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaneID", reflect.TypeOf((*MockTmuxClient)(nil).PaneID), target)
}

// PanePIDs mocks base method.
func (m *MockTmuxClient) PanePIDs() (map[int]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PanePIDs")
	ret0, _ := ret[0].(map[int]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PanePIDs indicates an expected call of PanePIDs.
func (mr *MockTmuxClientMockRecorder) PanePIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PanePIDs", reflect.TypeOf((*MockTmuxClient)(nil).PanePIDs))
}

// RenameWindow mocks base method.
func (m *MockTmuxClient) RenameWindow(target, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWindow", target, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameWindow indicates an expected call of RenameWindow.
func (mr *MockTmuxClientMockRecorder) RenameWindow(target, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWindow", reflect.TypeOf((*MockTmuxClient)(nil).RenameWindow), target, newName)
}

// SelectPane mocks base method.
func (m *MockTmuxClient) SelectPane(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPane", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SelectPane indicates an expected call of SelectPane.
func (mr *MockTmuxClientMockRecorder) SelectPane(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPane", reflect.TypeOf((*MockTmuxClient)(nil).SelectPane), target)
}

// SendKeys mocks base method.
func (m *MockTmuxClient) SendKeys(target, keys string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendKeys", target, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendKeys indicates an expected call of SendKeys.
func (mr *MockTmuxClientMockRecorder) SendKeys(target, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendKeys", reflect.TypeOf((*MockTmuxClient)(nil).SendKeys), target, keys)
}

// SendRawKeys mocks base method.
func (m *MockTmuxClient) SendRawKeys(target, keys string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRawKeys", target, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRawKeys indicates an expected call of SendRawKeys.
func (mr *MockTmuxClientMockRecorder) SendRawKeys(target, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRawKeys", reflect.TypeOf((*MockTmuxClient)(nil).SendRawKeys), target, keys)
}

// SessionName mocks base method.
func (m *MockTmuxClient) SessionName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionName indicates an expected call of SessionName.
func (mr *MockTmuxClientMockRecorder) SessionName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionName", reflect.TypeOf((*MockTmuxClient)(nil).SessionName))
}

// SetWindowHook mocks base method.
func (m *MockTmuxClient) SetWindowHook(target, hookName, command string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWindowHook", target, hookName, command)
}

// SetWindowHook indicates an expected call of SetWindowHook.
func (mr *MockTmuxClientMockRecorder) SetWindowHook(target, hookName, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWindowHook", reflect.TypeOf((*MockTmuxClient)(nil).SetWindowHook), target, hookName, command)
}

// SetWindowOption mocks base method.
func (m *MockTmuxClient) SetWindowOption(target, option, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWindowOption", target, option, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWindowOption indicates an expected call of SetWindowOption.
func (mr *MockTmuxClientMockRecorder) SetWindowOption(target, option, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWindowOption", reflect.TypeOf((*MockTmuxClient)(nil).SetWindowOption), target, option, value)
}

// SplitWindow mocks base method.
func (m *MockTmuxClient) SplitWindow(target string, cols int, cwd, command string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitWindow", target, cols, cwd, command)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitWindow indicates an expected call of SplitWindow.
func (mr *MockTmuxClientMockRecorder) SplitWindow(target, cols, cwd, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitWindow", reflect.TypeOf((*MockTmuxClient)(nil).SplitWindow), target, cols, cwd, command)
}

// SwitchToWindow mocks base method.
func (m *MockTmuxClient) SwitchToWindow(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchToWindow", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchToWindow indicates an expected call of SwitchToWindow.
func (mr *MockTmuxClientMockRecorder) SwitchToWindow(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToWindow", reflect.TypeOf((*MockTmuxClient)(nil).SwitchToWindow), target)
}

// WindowExists mocks base method.
func (m *MockTmuxClient) WindowExists(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowExists", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WindowExists indicates an expected call of WindowExists.
func (mr *MockTmuxClientMockRecorder) WindowExists(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowExists", reflect.TypeOf((*MockTmuxClient)(nil).WindowExists), name)
}

// WindowPanePIDs mocks base method.
func (m *MockTmuxClient) WindowPanePIDs(target string) (map[int]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowPanePIDs", target)
	ret0, _ := ret[0].(map[int]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WindowPanePIDs indicates an expected call of WindowPanePIDs.
func (mr *MockTmuxClientMockRecorder) WindowPanePIDs(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowPanePIDs", reflect.TypeOf((*MockTmuxClient)(nil).WindowPanePIDs), target)
}

// MockClaudeReader is a mock of ClaudeReader interface.
type MockClaudeReader struct {
	ctrl     *gomock.Controller
	recorder *MockClaudeReaderMockRecorder
	isgomock struct{}
}

// MockClaudeReaderMockRecorder is the mock recorder for MockClaudeReader.
type MockClaudeReaderMockRecorder struct {
	mock *MockClaudeReader
}

// NewMockClaudeReader creates a new mock instance.
func NewMockClaudeReader(ctrl *gomock.Controller) *MockClaudeReader {
	mock := &MockClaudeReader{ctrl: ctrl}
	mock.recorder = &MockClaudeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaudeReader) EXPECT() *MockClaudeReaderMockRecorder {
	return m.recorder
}

// CustomTitleFor mocks base method.
func (m *MockClaudeReader) CustomTitleFor(projectPath, sessionID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomTitleFor", projectPath, sessionID)
	ret0, _ := ret[0].(string)
	return ret0
}

// CustomTitleFor indicates an expected call of CustomTitleFor.
func (mr *MockClaudeReaderMockRecorder) CustomTitleFor(projectPath, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomTitleFor", reflect.TypeOf((*MockClaudeReader)(nil).CustomTitleFor), projectPath, sessionID)
}

// IsAlive mocks base method.
func (m *MockClaudeReader) IsAlive(pid int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlive", pid)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAlive indicates an expected call of IsAlive.
func (mr *MockClaudeReaderMockRecorder) IsAlive(pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlive", reflect.TypeOf((*MockClaudeReader)(nil).IsAlive), pid)
}

// IsDescendantOf mocks base method.
func (m *MockClaudeReader) IsDescendantOf(pid int, hostPIDs map[int]bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDescendantOf", pid, hostPIDs)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDescendantOf indicates an expected call of IsDescendantOf.
func (mr *MockClaudeReaderMockRecorder) IsDescendantOf(pid, hostPIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDescendantOf", reflect.TypeOf((*MockClaudeReader)(nil).IsDescendantOf), pid, hostPIDs)
}

// LastMessages mocks base method.
func (m *MockClaudeReader) LastMessages(projectPath, sessionID string, count int) []claude.SessionMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastMessages", projectPath, sessionID, count)
	ret0, _ := ret[0].([]claude.SessionMessage)
	return ret0
}

// LastMessages indicates an expected call of LastMessages.
func (mr *MockClaudeReaderMockRecorder) LastMessages(projectPath, sessionID, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastMessages", reflect.TypeOf((*MockClaudeReader)(nil).LastMessages), projectPath, sessionID, count)
}

// LiveSessions mocks base method.
func (m *MockClaudeReader) LiveSessions() ([]claude.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveSessions")
	ret0, _ := ret[0].([]claude.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiveSessions indicates an expected call of LiveSessions.
func (mr *MockClaudeReaderMockRecorder) LiveSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveSessions", reflect.TypeOf((*MockClaudeReader)(nil).LiveSessions))
}

// ProjectsDirForPath mocks base method.
func (m *MockClaudeReader) ProjectsDirForPath(projectPath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectsDirForPath", projectPath)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProjectsDirForPath indicates an expected call of ProjectsDirForPath.
func (mr *MockClaudeReaderMockRecorder) ProjectsDirForPath(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectsDirForPath", reflect.TypeOf((*MockClaudeReader)(nil).ProjectsDirForPath), projectPath)
}

// RecentSessions mocks base method.
func (m *MockClaudeReader) RecentSessions(projectPath string, maxResults int) []claude.RecentSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentSessions", projectPath, maxResults)
	ret0, _ := ret[0].([]claude.RecentSession)
	return ret0
}

// RecentSessions indicates an expected call of RecentSessions.
func (mr *MockClaudeReaderMockRecorder) RecentSessions(projectPath, maxResults any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentSessions", reflect.TypeOf((*MockClaudeReader)(nil).RecentSessions), projectPath, maxResults)
}

// SessionForPath mocks base method.
func (m *MockClaudeReader) SessionForPath(path string) *claude.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionForPath", path)
	ret0, _ := ret[0].(*claude.Session)
	return ret0
}

// SessionForPath indicates an expected call of SessionForPath.
func (mr *MockClaudeReaderMockRecorder) SessionForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionForPath", reflect.TypeOf((*MockClaudeReader)(nil).SessionForPath), path)
}

// SessionsForPath mocks base method.
func (m *MockClaudeReader) SessionsForPath(path string) []claude.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionsForPath", path)
	ret0, _ := ret[0].([]claude.Session)
	return ret0
}

// SessionsForPath indicates an expected call of SessionsForPath.
func (mr *MockClaudeReaderMockRecorder) SessionsForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionsForPath", reflect.TypeOf((*MockClaudeReader)(nil).SessionsForPath), path)
}
