package gitfiles

import (
	"context"
	"errors"
	"os/exec"
	"strings"
	"testing"

	moexec "github.com/rvanmech/unky-mo/internal/exec"
)

func TestClassify(t *testing.T) {
	gen := []byte("// Code generated by MockGen. DO NOT EDIT.\npackage x\n")
	cases := []struct {
		path, status string
		lines        int
		wsOnly       bool
		header       []byte
		want         Kind
	}{
		{"internal/web/server.go", "M", 10, false, []byte("package web\n"), KindLogic},
		{"internal/web/mocks/mock_deps.go", "M", 400, false, gen, KindGenerated},
		{"src/gen.ts", "A", 3, false, []byte("/* @generated */\n"), KindGenerated},
		{"go.sum", "M", 12, false, nil, KindGenerated},
		{"web/yarn.lock", "M", 12, false, nil, KindGenerated},
		{"vendor/github.com/x/y.go", "A", 50, false, nil, KindGenerated},
		{"static/app.min.js", "M", 1, false, nil, KindGenerated},
		{"api/v1/x.pb.go", "M", 1, false, nil, KindGenerated},
		{"internal/web/server_test.go", "M", 10, false, nil, KindTest},
		{"internal/web/server_test.go", "M", 10, true, nil, KindFormat},
		{"spec/models/user_spec.rb", "A", 10, false, nil, KindTest},
		{"app/models/user_spec.rb", "A", 10, false, nil, KindTest},
		{"src/ui/button.test.tsx", "M", 10, false, nil, KindTest},
		{"src/ui/button.spec.js", "M", 10, false, nil, KindTest},
		{"tests/test_api.py", "M", 10, false, nil, KindTest},
		{"internal/gitfiles/testdata/x.json", "A", 10, false, nil, KindTest},
		{"README.md", "M", 3, false, nil, KindDocs},
		{"docs/plans/x.html", "A", 3, false, nil, KindDocs},
		{"old.go", "R", 0, false, nil, KindRenamed},
		{"new.go", "R", 4, false, nil, KindLogic},
		{"internal/tui/app.go", "M", 6, true, nil, KindFormat},
		// A test file's name doesn't make generated code readable.
		{"internal/x/zz_generated_test.go", "M", 6, false, gen, KindGenerated},
		// The marker must be the Go convention's whole line, not a mention.
		{"internal/x/doc.go", "M", 6, false, []byte("// See \"Code generated ... DO NOT EDIT.\" in the spec\n"), KindLogic},
		{"internal/x/x_test.go", "M", 6, false, []byte("package x\n\tcase(\"/* @generated */\")\n"), KindTest},
		{"web/x.js", "M", 6, false, []byte("/**\n * @generated by codegen\n */\n"), KindGenerated},
		{"lib/x.py", "M", 6, false, []byte("# @generated\n"), KindGenerated},
	}
	for _, c := range cases {
		if got := Classify(c.path, c.status, c.lines, c.wsOnly, c.header); got != c.want {
			t.Errorf("Classify(%q, %q, %d, %v) = %q, want %q", c.path, c.status, c.lines, c.wsOnly, got, c.want)
		}
	}
}

func TestAreaOf(t *testing.T) {
	for in, want := range map[string]string{
		"CLAUDE.md":                     ".",
		"internal/web/static/editor.js": "internal/web",
		"internal/web/server.go":        "internal/web",
		"internal/doc.go":               "internal",
		"cmd/mo/main.go":                "cmd/mo",
		"docs/plans/x.md":               "docs",
		"app/models/user.rb":            "app/models",
		"config/routes.rb":              "config",
		"packages/ui/src/button.tsx":    "packages/ui",
	} {
		if got := AreaOf(in); got != want {
			t.Errorf("AreaOf(%q) = %q, want %q", in, got, want)
		}
	}
}

// branchRepo is newRepo (a.go, sub/b.go on main) plus a feature branch with
// one commit, then uncommitted edits on top:
//
//	committed:   a.go edited, c_test.go added, sub/b.go renamed to sub/b2.go
//	uncommitted: a.go edited again, ws.go whitespace-only, gen.go generated, new.md untracked
func branchRepo(t *testing.T) string {
	t.Helper()
	dir := newRepo(t)
	write(t, dir, "ws.go", "package x\nfunc f() {}\n")
	write(t, dir, "gen.go", "package x\n")
	write(t, dir, "sub/b.go", "b\nline two\nline three\n")
	run(t, dir, "add", ".")
	run(t, dir, "commit", "-m", "more")
	run(t, dir, "checkout", "-q", "-b", "feat")
	write(t, dir, "a.go", "one\ntwo\nthree\n")
	write(t, dir, "c_test.go", "package x\n")
	run(t, dir, "mv", "sub/b.go", "sub/b2.go")
	run(t, dir, "add", ".")
	run(t, dir, "commit", "-m", "feat work")
	write(t, dir, "a.go", "one\ntwo\nthree\nfour\n")
	write(t, dir, "ws.go", "package x\nfunc f()  {}\n")
	write(t, dir, "gen.go", "// Code generated by hand. DO NOT EDIT.\npackage x\n")
	write(t, dir, "new.md", "# new\nnotes\n")
	return dir
}

func overviewFiles(o *Overview) map[string]OverviewFile {
	m := map[string]OverviewFile{}
	for _, f := range o.Files {
		m[f.Path] = f
	}
	return m
}

func TestGetOverviewBranch(t *testing.T) {
	dir := branchRepo(t)
	o, err := GetOverview(context.Background(), moexec.DefaultCommander, dir+"/sub", ModeBranch)
	if err != nil {
		t.Fatal(err)
	}
	if o.Mode != ModeBranch || o.Fallback || o.Base != "main" || o.Branch != "feat" {
		t.Fatalf("mode/base: %+v", o)
	}
	if want := gitOut(t, dir, "rev-parse", "main"); o.MergeBase != want || o.Rev != want {
		t.Errorf("merge base %q, want %q", o.MergeBase, want)
	}
	files := overviewFiles(o)
	check := func(path, status string, kind Kind, added, removed int) {
		t.Helper()
		f, ok := files[path]
		if !ok {
			t.Errorf("%s missing from %+v", path, o.Files)
			return
		}
		if f.Status != status || f.Kind != kind || f.Added != added || f.Removed != removed {
			t.Errorf("%s: got %+v, want status %s kind %s +%d -%d", path, f, status, kind, added, removed)
		}
	}
	check("a.go", "M", KindLogic, 2, 0) // committed + uncommitted together
	check("c_test.go", "A", KindTest, 1, 0)
	check("ws.go", "M", KindFormat, 1, 1)
	check("gen.go", "M", KindGenerated, 1, 0)
	check("new.md", "?", KindDocs, 2, 0)
	check("sub/b2.go", "R", KindRenamed, 0, 0)
	if files["sub/b2.go"].OldPath != "sub/b.go" || files["sub/b2.go"].Area != "sub" || files["a.go"].Area != "." {
		t.Errorf("rename/area: %+v %+v", files["sub/b2.go"], files["a.go"])
	}
	if o.Kinds[KindLogic] != (KindTotal{Files: 1, Lines: 2}) || o.Kinds[KindFormat].Files != 1 {
		t.Errorf("kinds: %+v", o.Kinds)
	}
	if strings.Join(o.Areas, ",") != ".,sub" || o.Added != 7 || o.Removed != 1 {
		t.Errorf("areas %v, +%d -%d", o.Areas, o.Added, o.Removed)
	}
}

func TestGetOverviewHead(t *testing.T) {
	dir := branchRepo(t)
	o, err := GetOverview(context.Background(), moexec.DefaultCommander, dir, ModeHead)
	if err != nil {
		t.Fatal(err)
	}
	files := overviewFiles(o)
	if o.Mode != ModeHead || o.MergeBase != "" || o.Fallback || o.Rev != gitOut(t, dir, "rev-parse", "HEAD") {
		t.Errorf("mode: %+v", o)
	}
	// Only the uncommitted edits: the committed test file and rename are gone.
	if _, ok := files["c_test.go"]; ok {
		t.Errorf("committed file listed in head mode: %+v", o.Files)
	}
	if f := files["a.go"]; f.Added != 1 || f.Removed != 0 {
		t.Errorf("a.go: %+v", f)
	}
}

func TestGetOverviewFallsBack(t *testing.T) {
	ctx, cmd := context.Background(), moexec.DefaultCommander

	// On the default branch itself: just what's uncommitted.
	dir := newRepo(t)
	write(t, dir, "a.go", "changed\n")
	o, err := GetOverview(ctx, cmd, dir, ModeBranch)
	if err != nil {
		t.Fatal(err)
	}
	if o.Mode != ModeHead || !o.Fallback || len(o.Files) != 1 {
		t.Errorf("on main: %+v", o)
	}

	// No default branch to compare with.
	run(t, dir, "branch", "-m", "main", "trunk")
	if o, err = GetOverview(ctx, cmd, dir, ModeBranch); err != nil || o.Mode != ModeHead || !o.Fallback {
		t.Errorf("no default branch: %+v, %v", o, err)
	}

	// No commits yet: everything is untracked.
	empty := t.TempDir()
	if out, err := exec.Command("git", "init", "-b", "main", empty).CombinedOutput(); err != nil {
		t.Fatalf("git init: %v\n%s", err, out)
	}
	write(t, empty, "x.go", "package x\n")
	o, err = GetOverview(ctx, cmd, empty, ModeBranch)
	if err != nil {
		t.Fatal(err)
	}
	if len(o.Files) != 1 || o.Files[0].Status != "?" || o.Files[0].Added != 1 {
		t.Errorf("no commits: %+v", o)
	}

	if _, err := GetOverview(ctx, cmd, t.TempDir(), ModeBranch); !errors.Is(err, ErrNotRepo) {
		t.Errorf("not a repo: %v", err)
	}
}

func TestReadAt(t *testing.T) {
	dir := branchRepo(t)
	ctx, cmd := context.Background(), moexec.DefaultCommander
	mb := gitOut(t, dir, "rev-parse", "main")

	c, err := ReadAt(ctx, cmd, dir, mb, "sub/b.go") // renamed away since
	if err != nil || !c.Exists || c.Text != "b\nline two\nline three\n" {
		t.Errorf("old path: %+v, %v", c, err)
	}
	if c, err := ReadAt(ctx, cmd, dir, mb, "c_test.go"); err != nil || c.Exists {
		t.Errorf("not in base: %+v, %v", c, err)
	}
	tree := gitOut(t, dir, "rev-parse", "main^{tree}")
	for _, rev := range []string{"main", "HEAD", mb[:7], "--output=/tmp/x", tree, strings.Repeat("0", 40)} {
		if _, err := ReadAt(ctx, cmd, dir, rev, "a.go"); !errors.Is(err, ErrUnknownCommit) {
			t.Errorf("rev %q: got %v, want ErrUnknownCommit", rev, err)
		}
	}
	if _, err := ReadAt(ctx, cmd, dir, mb, "../x"); !errors.Is(err, ErrOutsideRoot) {
		t.Errorf("traversal: %v", err)
	}
}

func gitOut(t *testing.T, dir string, args ...string) string {
	t.Helper()
	out, err := exec.Command("git", append([]string{"-C", dir}, args...)...).Output()
	if err != nil {
		t.Fatalf("git %v: %v", args, err)
	}
	return strings.TrimSpace(string(out))
}
