package gitfiles

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"testing"

	moexec "github.com/rvanmech/unky-mo/internal/exec"
)

// selectionRepo is newRepo plus this history on main, and returns each
// commit's id by name:
//
//	r ─ c1 ─ c2 ─ c3 ─────── m ─ c5      (main)
//	          └─ s1 ─ s2 ───┘            (side, merged by m)
//
// c1 edits a.go, c2 renames sub/b.go, c3 adds a generated gen.go and edits
// a.go, s1/s2 add and edit side.go, c5 edits a.go. The working tree is left
// with an uncommitted edit that must never show up.
func selectionRepo(t *testing.T) (string, map[string]string) {
	t.Helper()
	dir := newRepo(t)
	ids := map[string]string{"r": gitOut(t, dir, "rev-parse", "HEAD")}
	commit := func(name string) {
		run(t, dir, "add", "-A")
		run(t, dir, "commit", "-q", "-m", name)
		ids[name] = gitOut(t, dir, "rev-parse", "HEAD")
	}
	write(t, dir, "a.go", "one\ntwo\nthree\n")
	commit("c1")
	run(t, dir, "mv", "sub/b.go", "sub/b2.go")
	commit("c2")
	run(t, dir, "checkout", "-q", "-b", "side")
	write(t, dir, "side.go", "package x\n")
	commit("s1")
	write(t, dir, "side.go", "package x\n\nfunc s() {}\n")
	commit("s2")
	run(t, dir, "checkout", "-q", "main")
	write(t, dir, "gen.go", "// Code generated by hand. DO NOT EDIT.\npackage x\n")
	write(t, dir, "a.go", "one\ntwo\nthree\nfour\n")
	commit("c3")
	run(t, dir, "merge", "-q", "--no-ff", "-m", "m", "side")
	ids["m"] = gitOut(t, dir, "rev-parse", "HEAD")
	write(t, dir, "a.go", "one\ntwo\nthree\nfour\nfive\n")
	commit("c5")
	write(t, dir, "a.go", "uncommitted\n")
	return dir, ids
}

func TestResolveSelection(t *testing.T) {
	dir, ids := selectionRepo(t)
	ctx, cmd := context.Background(), moexec.DefaultCommander
	pick := func(names ...string) []string {
		var out []string
		for _, n := range names {
			out = append(out, ids[n])
		}
		return out
	}

	for _, tc := range []struct {
		names      []string
		base, head string
	}{
		{[]string{"c2"}, "c1", "c2"},
		{[]string{"c2", "c3"}, "c1", "c3"},
		{[]string{"c3", "c1", "c2", "c1"}, "r", "c3"},
		{[]string{"m", "s2", "c3", "s1"}, "c2", "m"},
		{[]string{"c5", "m", "c3", "s2", "s1"}, "c2", "c5"},
	} {
		s, err := ResolveSelection(ctx, cmd, dir+"/sub", pick(tc.names...))
		if err != nil {
			t.Errorf("%v: %v", tc.names, err)
			continue
		}
		if s.Base != ids[tc.base] || s.Head != ids[tc.head] || s.Root != gitOut(t, dir, "rev-parse", "--show-toplevel") {
			t.Errorf("%v: %+v, want %s..%s", tc.names, s, tc.base, tc.head)
		}
	}

	for _, tc := range []struct {
		names         []string
		reason        string
		commit, other string
	}{
		{[]string{"c1", "c3"}, "gap", "c2", ""},
		{[]string{"c1", "c3", "c5"}, "gap", "c2", ""},
		// s1 and s2 fork off c2 and come back in m: left out in between.
		{[]string{"c1", "c2", "c3", "m"}, "gap", "s1", ""},
		{[]string{"c3", "m"}, "merge", "m", "s2"},
		{[]string{"m", "c5"}, "merge", "m", "c3"},
		{[]string{"c3", "s2"}, "heads", "", ""},
		{[]string{"r", "c1"}, "root", "r", ""},
	} {
		_, err := ResolveSelection(ctx, cmd, dir, pick(tc.names...))
		var se *SelectionError
		if !errors.As(err, &se) || se.Reason != tc.reason {
			t.Errorf("%v: %v, want %s", tc.names, err, tc.reason)
			continue
		}
		if tc.commit != "" && se.Commit != ids[tc.commit] || tc.other != "" && se.Other != ids[tc.other] {
			t.Errorf("%v: %+v, want commit %s other %s", tc.names, se, tc.commit, tc.other)
		}
		if tc.reason == "heads" && !(se.Commit == ids["c3"] && se.Other == ids["s2"] || se.Commit == ids["s2"] && se.Other == ids["c3"]) {
			t.Errorf("heads: %+v", se)
		}
		if se.Error() == "" {
			t.Errorf("%v: empty message", tc.names)
		}
	}

	tooMany := make([]string, MaxSelection+1)
	for i := range tooMany {
		tooMany[i] = fmt.Sprintf("%040x", i)
	}
	for name, hashes := range map[string][]string{
		"empty":    nil,
		"too many": tooMany,
		"short":    {ids["c2"][:7]},
		"ref":      {"HEAD"},
		"option":   {"--all"},
		"upper":    {strings.ToUpper(ids["c2"])},
	} {
		if _, err := ResolveSelection(ctx, cmd, dir, hashes); !errors.Is(err, ErrBadSelection) {
			t.Errorf("%s: %v", name, err)
		}
	}

	tree := gitOut(t, dir, "rev-parse", ids["c2"]+"^{tree}")
	blob := gitOut(t, dir, "rev-parse", ids["c2"]+":a.go")
	run(t, dir, "tag", "-a", "-m", "tag", "v1", ids["c2"])
	tag := gitOut(t, dir, "rev-parse", "v1")
	for name, hashes := range map[string][]string{
		"tree":    {tree},
		"blob":    {blob},
		"tag":     {tag},
		"missing": {strings.Repeat("ab", 20)},
		"mixed":   {ids["c2"], tree},
	} {
		if _, err := ResolveSelection(ctx, cmd, dir, hashes); !errors.Is(err, ErrUnknownCommit) {
			t.Errorf("%s: %v", name, err)
		}
	}
}

func TestGetOverviewRange(t *testing.T) {
	dir, ids := selectionRepo(t)
	ctx, cmd := context.Background(), moexec.DefaultCommander
	o, err := GetOverviewRange(ctx, cmd, dir, ids["c1"], ids["c3"])
	if err != nil {
		t.Fatal(err)
	}
	if o.Mode != ModeCommits || o.Rev != ids["c1"] || o.MergeBase != ids["c1"] || o.Head != ids["c3"] || o.Base != "" || o.Fallback || o.Branch != "main" {
		t.Errorf("overview %+v", o)
	}
	files := overviewFiles(o)
	if f := files["a.go"]; f.Added != 1 || f.Removed != 0 || f.Kind != KindLogic {
		t.Errorf("a.go from c3, not the working tree: %+v", f)
	}
	if files["gen.go"].Kind != KindGenerated || files["sub/b2.go"].OldPath != "sub/b.go" || files["sub/b2.go"].Kind != KindRenamed {
		t.Errorf("files %+v", o.Files)
	}
	if _, ok := files["side.go"]; ok || len(o.Files) != 3 {
		t.Errorf("files %+v", o.Files)
	}
	if o.Added != 3 || o.Removed != 0 {
		t.Errorf("totals +%d -%d", o.Added, o.Removed)
	}

	tree := gitOut(t, dir, "rev-parse", ids["c2"]+"^{tree}")
	for name, pair := range map[string][2]string{
		"short base": {ids["c1"][:7], ids["c3"]},
		"ref head":   {ids["c1"], "HEAD"},
		"tree head":  {ids["c1"], tree},
	} {
		if _, err := GetOverviewRange(ctx, cmd, dir, pair[0], pair[1]); !errors.Is(err, ErrUnknownCommit) {
			t.Errorf("%s: %v", name, err)
		}
	}
}
