// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rvanmech/unky-mo/internal/tui/sidebar (interfaces: TmuxClient,ClaudeReader,WindowResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_deps.go -package=mock_sidebar github.com/rvanmech/unky-mo/internal/tui/sidebar TmuxClient,ClaudeReader,WindowResolver
//

// Package mock_sidebar is a generated GoMock package.
package mock_sidebar

import (
	reflect "reflect"

	claude "github.com/rvanmech/unky-mo/internal/claude"
	gomock "go.uber.org/mock/gomock"
)

// MockTmuxClient is a mock of TmuxClient interface.
type MockTmuxClient struct {
	ctrl     *gomock.Controller
	recorder *MockTmuxClientMockRecorder
	isgomock struct{}
}

// MockTmuxClientMockRecorder is the mock recorder for MockTmuxClient.
type MockTmuxClientMockRecorder struct {
	mock *MockTmuxClient
}

// NewMockTmuxClient creates a new mock instance.
func NewMockTmuxClient(ctrl *gomock.Controller) *MockTmuxClient {
	mock := &MockTmuxClient{ctrl: ctrl}
	mock.recorder = &MockTmuxClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTmuxClient) EXPECT() *MockTmuxClientMockRecorder {
	return m.recorder
}

// BindKey mocks base method.
func (m *MockTmuxClient) BindKey(table, key, command string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{table, key, command}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BindKey", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindKey indicates an expected call of BindKey.
func (mr *MockTmuxClientMockRecorder) BindKey(table, key, command any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{table, key, command}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindKey", reflect.TypeOf((*MockTmuxClient)(nil).BindKey), varargs...)
}

// BreakPane mocks base method.
func (m *MockTmuxClient) BreakPane(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BreakPane", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BreakPane indicates an expected call of BreakPane.
func (mr *MockTmuxClientMockRecorder) BreakPane(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreakPane", reflect.TypeOf((*MockTmuxClient)(nil).BreakPane), paneID)
}

// BreakPaneToSession mocks base method.
func (m *MockTmuxClient) BreakPaneToSession(paneID, session string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BreakPaneToSession", paneID, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// BreakPaneToSession indicates an expected call of BreakPaneToSession.
func (mr *MockTmuxClientMockRecorder) BreakPaneToSession(paneID, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BreakPaneToSession", reflect.TypeOf((*MockTmuxClient)(nil).BreakPaneToSession), paneID, session)
}

// ConfigureStatusFormat mocks base method.
func (m *MockTmuxClient) ConfigureStatusFormat() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ConfigureStatusFormat")
}

// ConfigureStatusFormat indicates an expected call of ConfigureStatusFormat.
func (mr *MockTmuxClientMockRecorder) ConfigureStatusFormat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureStatusFormat", reflect.TypeOf((*MockTmuxClient)(nil).ConfigureStatusFormat))
}

// DisplayPopupAttach mocks base method.
func (m *MockTmuxClient) DisplayPopupAttach(session, cwd, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayPopupAttach", session, cwd, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisplayPopupAttach indicates an expected call of DisplayPopupAttach.
func (mr *MockTmuxClientMockRecorder) DisplayPopupAttach(session, cwd, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayPopupAttach", reflect.TypeOf((*MockTmuxClient)(nil).DisplayPopupAttach), session, cwd, title)
}

// IsPaneAlive mocks base method.
func (m *MockTmuxClient) IsPaneAlive(paneID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPaneAlive", paneID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPaneAlive indicates an expected call of IsPaneAlive.
func (mr *MockTmuxClientMockRecorder) IsPaneAlive(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPaneAlive", reflect.TypeOf((*MockTmuxClient)(nil).IsPaneAlive), paneID)
}

// JoinPaneConsolidate mocks base method.
func (m *MockTmuxClient) JoinPaneConsolidate(srcPaneID, dstPaneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinPaneConsolidate", srcPaneID, dstPaneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinPaneConsolidate indicates an expected call of JoinPaneConsolidate.
func (mr *MockTmuxClientMockRecorder) JoinPaneConsolidate(srcPaneID, dstPaneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinPaneConsolidate", reflect.TypeOf((*MockTmuxClient)(nil).JoinPaneConsolidate), srcPaneID, dstPaneID)
}

// JoinPaneVertical mocks base method.
func (m *MockTmuxClient) JoinPaneVertical(srcPaneID, dstTarget string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinPaneVertical", srcPaneID, dstTarget)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinPaneVertical indicates an expected call of JoinPaneVertical.
func (mr *MockTmuxClientMockRecorder) JoinPaneVertical(srcPaneID, dstTarget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinPaneVertical", reflect.TypeOf((*MockTmuxClient)(nil).JoinPaneVertical), srcPaneID, dstTarget)
}

// KillPane mocks base method.
func (m *MockTmuxClient) KillPane(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KillPane", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// KillPane indicates an expected call of KillPane.
func (mr *MockTmuxClientMockRecorder) KillPane(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KillPane", reflect.TypeOf((*MockTmuxClient)(nil).KillPane), paneID)
}

// NewDetachedSession mocks base method.
func (m *MockTmuxClient) NewDetachedSession(name, cwd string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDetachedSession", name, cwd)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDetachedSession indicates an expected call of NewDetachedSession.
func (mr *MockTmuxClientMockRecorder) NewDetachedSession(name, cwd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDetachedSession", reflect.TypeOf((*MockTmuxClient)(nil).NewDetachedSession), name, cwd)
}

// SelectPane mocks base method.
func (m *MockTmuxClient) SelectPane(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPane", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SelectPane indicates an expected call of SelectPane.
func (mr *MockTmuxClientMockRecorder) SelectPane(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPane", reflect.TypeOf((*MockTmuxClient)(nil).SelectPane), target)
}

// SelectWindowByPane mocks base method.
func (m *MockTmuxClient) SelectWindowByPane(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectWindowByPane", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SelectWindowByPane indicates an expected call of SelectWindowByPane.
func (mr *MockTmuxClientMockRecorder) SelectWindowByPane(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWindowByPane", reflect.TypeOf((*MockTmuxClient)(nil).SelectWindowByPane), paneID)
}

// SessionExistsNamed mocks base method.
func (m *MockTmuxClient) SessionExistsNamed(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionExistsNamed", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SessionExistsNamed indicates an expected call of SessionExistsNamed.
func (mr *MockTmuxClientMockRecorder) SessionExistsNamed(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionExistsNamed", reflect.TypeOf((*MockTmuxClient)(nil).SessionExistsNamed), name)
}

// SessionName mocks base method.
func (m *MockTmuxClient) SessionName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionName")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionName indicates an expected call of SessionName.
func (mr *MockTmuxClientMockRecorder) SessionName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionName", reflect.TypeOf((*MockTmuxClient)(nil).SessionName))
}

// SetSessionOption mocks base method.
func (m *MockTmuxClient) SetSessionOption(session, option, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionOption", session, option, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionOption indicates an expected call of SetSessionOption.
func (mr *MockTmuxClientMockRecorder) SetSessionOption(session, option, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionOption", reflect.TypeOf((*MockTmuxClient)(nil).SetSessionOption), session, option, value)
}

// SetWindowOption mocks base method.
func (m *MockTmuxClient) SetWindowOption(target, option, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWindowOption", target, option, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWindowOption indicates an expected call of SetWindowOption.
func (mr *MockTmuxClientMockRecorder) SetWindowOption(target, option, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWindowOption", reflect.TypeOf((*MockTmuxClient)(nil).SetWindowOption), target, option, value)
}

// SplitWindowHorizontal mocks base method.
func (m *MockTmuxClient) SplitWindowHorizontal(target, cwd string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SplitWindowHorizontal", target, cwd)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SplitWindowHorizontal indicates an expected call of SplitWindowHorizontal.
func (mr *MockTmuxClientMockRecorder) SplitWindowHorizontal(target, cwd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SplitWindowHorizontal", reflect.TypeOf((*MockTmuxClient)(nil).SplitWindowHorizontal), target, cwd)
}

// SwitchToWindow mocks base method.
func (m *MockTmuxClient) SwitchToWindow(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchToWindow", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchToWindow indicates an expected call of SwitchToWindow.
func (mr *MockTmuxClientMockRecorder) SwitchToWindow(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToWindow", reflect.TypeOf((*MockTmuxClient)(nil).SwitchToWindow), target)
}

// UnbindKey mocks base method.
func (m *MockTmuxClient) UnbindKey(table, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnbindKey", table, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnbindKey indicates an expected call of UnbindKey.
func (mr *MockTmuxClientMockRecorder) UnbindKey(table, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnbindKey", reflect.TypeOf((*MockTmuxClient)(nil).UnbindKey), table, key)
}

// WindowPanePIDs mocks base method.
func (m *MockTmuxClient) WindowPanePIDs(target string) (map[int]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowPanePIDs", target)
	ret0, _ := ret[0].(map[int]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WindowPanePIDs indicates an expected call of WindowPanePIDs.
func (mr *MockTmuxClientMockRecorder) WindowPanePIDs(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowPanePIDs", reflect.TypeOf((*MockTmuxClient)(nil).WindowPanePIDs), target)
}

// MockClaudeReader is a mock of ClaudeReader interface.
type MockClaudeReader struct {
	ctrl     *gomock.Controller
	recorder *MockClaudeReaderMockRecorder
	isgomock struct{}
}

// MockClaudeReaderMockRecorder is the mock recorder for MockClaudeReader.
type MockClaudeReaderMockRecorder struct {
	mock *MockClaudeReader
}

// NewMockClaudeReader creates a new mock instance.
func NewMockClaudeReader(ctrl *gomock.Controller) *MockClaudeReader {
	mock := &MockClaudeReader{ctrl: ctrl}
	mock.recorder = &MockClaudeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaudeReader) EXPECT() *MockClaudeReaderMockRecorder {
	return m.recorder
}

// ActiveShellsForSession mocks base method.
func (m *MockClaudeReader) ActiveShellsForSession(projectPath string) []claude.ActiveShell {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveShellsForSession", projectPath)
	ret0, _ := ret[0].([]claude.ActiveShell)
	return ret0
}

// ActiveShellsForSession indicates an expected call of ActiveShellsForSession.
func (mr *MockClaudeReaderMockRecorder) ActiveShellsForSession(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveShellsForSession", reflect.TypeOf((*MockClaudeReader)(nil).ActiveShellsForSession), projectPath)
}

// FormatShellCommand mocks base method.
func (m *MockClaudeReader) FormatShellCommand(cmd string, maxLen int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatShellCommand", cmd, maxLen)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatShellCommand indicates an expected call of FormatShellCommand.
func (mr *MockClaudeReaderMockRecorder) FormatShellCommand(cmd, maxLen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatShellCommand", reflect.TypeOf((*MockClaudeReader)(nil).FormatShellCommand), cmd, maxLen)
}

// IsDescendantOf mocks base method.
func (m *MockClaudeReader) IsDescendantOf(pid int, hostPIDs map[int]bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDescendantOf", pid, hostPIDs)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDescendantOf indicates an expected call of IsDescendantOf.
func (mr *MockClaudeReaderMockRecorder) IsDescendantOf(pid, hostPIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDescendantOf", reflect.TypeOf((*MockClaudeReader)(nil).IsDescendantOf), pid, hostPIDs)
}

// LiveSessions mocks base method.
func (m *MockClaudeReader) LiveSessions() ([]claude.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveSessions")
	ret0, _ := ret[0].([]claude.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiveSessions indicates an expected call of LiveSessions.
func (mr *MockClaudeReaderMockRecorder) LiveSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveSessions", reflect.TypeOf((*MockClaudeReader)(nil).LiveSessions))
}

// ProjectsDirForPath mocks base method.
func (m *MockClaudeReader) ProjectsDirForPath(projectPath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectsDirForPath", projectPath)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProjectsDirForPath indicates an expected call of ProjectsDirForPath.
func (mr *MockClaudeReaderMockRecorder) ProjectsDirForPath(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectsDirForPath", reflect.TypeOf((*MockClaudeReader)(nil).ProjectsDirForPath), projectPath)
}

// SessionForPath mocks base method.
func (m *MockClaudeReader) SessionForPath(path string) *claude.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionForPath", path)
	ret0, _ := ret[0].(*claude.Session)
	return ret0
}

// SessionForPath indicates an expected call of SessionForPath.
func (mr *MockClaudeReaderMockRecorder) SessionForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionForPath", reflect.TypeOf((*MockClaudeReader)(nil).SessionForPath), path)
}

// SessionsForPath mocks base method.
func (m *MockClaudeReader) SessionsForPath(path string) []claude.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionsForPath", path)
	ret0, _ := ret[0].([]claude.Session)
	return ret0
}

// SessionsForPath indicates an expected call of SessionsForPath.
func (mr *MockClaudeReaderMockRecorder) SessionsForPath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionsForPath", reflect.TypeOf((*MockClaudeReader)(nil).SessionsForPath), path)
}

// MockWindowResolver is a mock of WindowResolver interface.
type MockWindowResolver struct {
	ctrl     *gomock.Controller
	recorder *MockWindowResolverMockRecorder
	isgomock struct{}
}

// MockWindowResolverMockRecorder is the mock recorder for MockWindowResolver.
type MockWindowResolverMockRecorder struct {
	mock *MockWindowResolver
}

// NewMockWindowResolver creates a new mock instance.
func NewMockWindowResolver(ctrl *gomock.Controller) *MockWindowResolver {
	mock := &MockWindowResolver{ctrl: ctrl}
	mock.recorder = &MockWindowResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindowResolver) EXPECT() *MockWindowResolverMockRecorder {
	return m.recorder
}

// ResolveOwnWindow mocks base method.
func (m *MockWindowResolver) ResolveOwnWindow() (string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveOwnWindow")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// ResolveOwnWindow indicates an expected call of ResolveOwnWindow.
func (mr *MockWindowResolverMockRecorder) ResolveOwnWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveOwnWindow", reflect.TypeOf((*MockWindowResolver)(nil).ResolveOwnWindow))
}
