// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rvanmech/unky-mo/internal/web (interfaces: StateReader,ProjectLister,WorktreeReader,PRClient,TicketSource,PromptSender,SessionHistory,SessionOps)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_deps.go -package=mock_web github.com/rvanmech/unky-mo/internal/web StateReader,ProjectLister,WorktreeReader,PRClient,TicketSource,PromptSender,SessionHistory,SessionOps
//

// Package mock_web is a generated GoMock package.
package mock_web

import (
	context "context"
	reflect "reflect"

	claude "github.com/rvanmech/unky-mo/internal/claude"
	github "github.com/rvanmech/unky-mo/internal/github"
	ops "github.com/rvanmech/unky-mo/internal/ops"
	project "github.com/rvanmech/unky-mo/internal/project"
	state "github.com/rvanmech/unky-mo/internal/state"
	tickets "github.com/rvanmech/unky-mo/internal/tickets"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockStateReader) Read() (*state.StateFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(*state.StateFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockStateReaderMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockStateReader)(nil).Read))
}

// MockProjectLister is a mock of ProjectLister interface.
type MockProjectLister struct {
	ctrl     *gomock.Controller
	recorder *MockProjectListerMockRecorder
	isgomock struct{}
}

// MockProjectListerMockRecorder is the mock recorder for MockProjectLister.
type MockProjectListerMockRecorder struct {
	mock *MockProjectLister
}

// NewMockProjectLister creates a new mock instance.
func NewMockProjectLister(ctrl *gomock.Controller) *MockProjectLister {
	mock := &MockProjectLister{ctrl: ctrl}
	mock.recorder = &MockProjectListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectLister) EXPECT() *MockProjectListerMockRecorder {
	return m.recorder
}

// LoadProjects mocks base method.
func (m *MockProjectLister) LoadProjects() ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProjects")
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProjects indicates an expected call of LoadProjects.
func (mr *MockProjectListerMockRecorder) LoadProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProjects", reflect.TypeOf((*MockProjectLister)(nil).LoadProjects))
}

// MockWorktreeReader is a mock of WorktreeReader interface.
type MockWorktreeReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorktreeReaderMockRecorder
	isgomock struct{}
}

// MockWorktreeReaderMockRecorder is the mock recorder for MockWorktreeReader.
type MockWorktreeReaderMockRecorder struct {
	mock *MockWorktreeReader
}

// NewMockWorktreeReader creates a new mock instance.
func NewMockWorktreeReader(ctrl *gomock.Controller) *MockWorktreeReader {
	mock := &MockWorktreeReader{ctrl: ctrl}
	mock.recorder = &MockWorktreeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorktreeReader) EXPECT() *MockWorktreeReaderMockRecorder {
	return m.recorder
}

// ListBranches mocks base method.
func (m *MockWorktreeReader) ListBranches(projectPath string) ([]project.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", projectPath)
	ret0, _ := ret[0].([]project.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockWorktreeReaderMockRecorder) ListBranches(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockWorktreeReader)(nil).ListBranches), projectPath)
}

// MockPRClient is a mock of PRClient interface.
type MockPRClient struct {
	ctrl     *gomock.Controller
	recorder *MockPRClientMockRecorder
	isgomock struct{}
}

// MockPRClientMockRecorder is the mock recorder for MockPRClient.
type MockPRClientMockRecorder struct {
	mock *MockPRClient
}

// NewMockPRClient creates a new mock instance.
func NewMockPRClient(ctrl *gomock.Controller) *MockPRClient {
	mock := &MockPRClient{ctrl: ctrl}
	mock.recorder = &MockPRClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRClient) EXPECT() *MockPRClientMockRecorder {
	return m.recorder
}

// GetPRDetail mocks base method.
func (m *MockPRClient) GetPRDetail(projectPath string, number int) (*github.PRDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRDetail", projectPath, number)
	ret0, _ := ret[0].(*github.PRDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRDetail indicates an expected call of GetPRDetail.
func (mr *MockPRClientMockRecorder) GetPRDetail(projectPath, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRDetail", reflect.TypeOf((*MockPRClient)(nil).GetPRDetail), projectPath, number)
}

// ListPRs mocks base method.
func (m *MockPRClient) ListPRs(projectPath string) ([]github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRs", projectPath)
	ret0, _ := ret[0].([]github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPRs indicates an expected call of ListPRs.
func (mr *MockPRClientMockRecorder) ListPRs(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRs", reflect.TypeOf((*MockPRClient)(nil).ListPRs), projectPath)
}

// MockTicketSource is a mock of TicketSource interface.
type MockTicketSource struct {
	ctrl     *gomock.Controller
	recorder *MockTicketSourceMockRecorder
	isgomock struct{}
}

// MockTicketSourceMockRecorder is the mock recorder for MockTicketSource.
type MockTicketSourceMockRecorder struct {
	mock *MockTicketSource
}

// NewMockTicketSource creates a new mock instance.
func NewMockTicketSource(ctrl *gomock.Controller) *MockTicketSource {
	mock := &MockTicketSource{ctrl: ctrl}
	mock.recorder = &MockTicketSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketSource) EXPECT() *MockTicketSourceMockRecorder {
	return m.recorder
}

// Detail mocks base method.
func (m *MockTicketSource) Detail(ctx context.Context, providerName, id string) (*tickets.TicketDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, providerName, id)
	ret0, _ := ret[0].(*tickets.TicketDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockTicketSourceMockRecorder) Detail(ctx, providerName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTicketSource)(nil).Detail), ctx, providerName, id)
}

// MyTickets mocks base method.
func (m *MockTicketSource) MyTickets(ctx context.Context) ([]tickets.Ticket, []tickets.FetchResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MyTickets", ctx)
	ret0, _ := ret[0].([]tickets.Ticket)
	ret1, _ := ret[1].([]tickets.FetchResult)
	return ret0, ret1
}

// MyTickets indicates an expected call of MyTickets.
func (mr *MockTicketSourceMockRecorder) MyTickets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MyTickets", reflect.TypeOf((*MockTicketSource)(nil).MyTickets), ctx)
}

// MockPromptSender is a mock of PromptSender interface.
type MockPromptSender struct {
	ctrl     *gomock.Controller
	recorder *MockPromptSenderMockRecorder
	isgomock struct{}
}

// MockPromptSenderMockRecorder is the mock recorder for MockPromptSender.
type MockPromptSenderMockRecorder struct {
	mock *MockPromptSender
}

// NewMockPromptSender creates a new mock instance.
func NewMockPromptSender(ctrl *gomock.Controller) *MockPromptSender {
	mock := &MockPromptSender{ctrl: ctrl}
	mock.recorder = &MockPromptSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptSender) EXPECT() *MockPromptSenderMockRecorder {
	return m.recorder
}

// SendLiteralText mocks base method.
func (m *MockPromptSender) SendLiteralText(target, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLiteralText", target, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLiteralText indicates an expected call of SendLiteralText.
func (mr *MockPromptSenderMockRecorder) SendLiteralText(target, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLiteralText", reflect.TypeOf((*MockPromptSender)(nil).SendLiteralText), target, text)
}

// MockSessionHistory is a mock of SessionHistory interface.
type MockSessionHistory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionHistoryMockRecorder
	isgomock struct{}
}

// MockSessionHistoryMockRecorder is the mock recorder for MockSessionHistory.
type MockSessionHistoryMockRecorder struct {
	mock *MockSessionHistory
}

// NewMockSessionHistory creates a new mock instance.
func NewMockSessionHistory(ctrl *gomock.Controller) *MockSessionHistory {
	mock := &MockSessionHistory{ctrl: ctrl}
	mock.recorder = &MockSessionHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionHistory) EXPECT() *MockSessionHistoryMockRecorder {
	return m.recorder
}

// RecentSessions mocks base method.
func (m *MockSessionHistory) RecentSessions(path string, n int) []claude.RecentSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentSessions", path, n)
	ret0, _ := ret[0].([]claude.RecentSession)
	return ret0
}

// RecentSessions indicates an expected call of RecentSessions.
func (mr *MockSessionHistoryMockRecorder) RecentSessions(path, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentSessions", reflect.TypeOf((*MockSessionHistory)(nil).RecentSessions), path, n)
}

// TranscriptExists mocks base method.
func (m *MockSessionHistory) TranscriptExists(path, sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptExists", path, sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TranscriptExists indicates an expected call of TranscriptExists.
func (mr *MockSessionHistoryMockRecorder) TranscriptExists(path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptExists", reflect.TypeOf((*MockSessionHistory)(nil).TranscriptExists), path, sessionID)
}

// MockSessionOps is a mock of SessionOps interface.
type MockSessionOps struct {
	ctrl     *gomock.Controller
	recorder *MockSessionOpsMockRecorder
	isgomock struct{}
}

// MockSessionOpsMockRecorder is the mock recorder for MockSessionOps.
type MockSessionOpsMockRecorder struct {
	mock *MockSessionOps
}

// NewMockSessionOps creates a new mock instance.
func NewMockSessionOps(ctrl *gomock.Controller) *MockSessionOps {
	mock := &MockSessionOps{ctrl: ctrl}
	mock.recorder = &MockSessionOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionOps) EXPECT() *MockSessionOpsMockRecorder {
	return m.recorder
}

// CleanupWorktree mocks base method.
func (m *MockSessionOps) CleanupWorktree(p ops.CleanupParams) (*ops.CleanupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupWorktree", p)
	ret0, _ := ret[0].(*ops.CleanupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupWorktree indicates an expected call of CleanupWorktree.
func (mr *MockSessionOpsMockRecorder) CleanupWorktree(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupWorktree", reflect.TypeOf((*MockSessionOps)(nil).CleanupWorktree), p)
}

// CreateWorktreeAndLaunch mocks base method.
func (m *MockSessionOps) CreateWorktreeAndLaunch(p ops.WorktreeParams) (*ops.WorktreeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorktreeAndLaunch", p)
	ret0, _ := ret[0].(*ops.WorktreeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorktreeAndLaunch indicates an expected call of CreateWorktreeAndLaunch.
func (mr *MockSessionOpsMockRecorder) CreateWorktreeAndLaunch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorktreeAndLaunch", reflect.TypeOf((*MockSessionOps)(nil).CreateWorktreeAndLaunch), p)
}

// IsDirty mocks base method.
func (m *MockSessionOps) IsDirty(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockSessionOpsMockRecorder) IsDirty(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockSessionOps)(nil).IsDirty), path)
}

// Launch mocks base method.
func (m *MockSessionOps) Launch(p ops.LaunchParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Launch indicates an expected call of Launch.
func (mr *MockSessionOpsMockRecorder) Launch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockSessionOps)(nil).Launch), p)
}

// LaunchSibling mocks base method.
func (m *MockSessionOps) LaunchSibling(p ops.SiblingParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LaunchSibling", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LaunchSibling indicates an expected call of LaunchSibling.
func (mr *MockSessionOpsMockRecorder) LaunchSibling(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaunchSibling", reflect.TypeOf((*MockSessionOps)(nil).LaunchSibling), p)
}

// LiftSessionToWorktree mocks base method.
func (m *MockSessionOps) LiftSessionToWorktree(p ops.LiftParams) (*ops.LiftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiftSessionToWorktree", p)
	ret0, _ := ret[0].(*ops.LiftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiftSessionToWorktree indicates an expected call of LiftSessionToWorktree.
func (mr *MockSessionOpsMockRecorder) LiftSessionToWorktree(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiftSessionToWorktree", reflect.TypeOf((*MockSessionOps)(nil).LiftSessionToWorktree), p)
}

// LiveSessions mocks base method.
func (m *MockSessionOps) LiveSessions() ([]claude.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveSessions")
	ret0, _ := ret[0].([]claude.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiveSessions indicates an expected call of LiveSessions.
func (mr *MockSessionOpsMockRecorder) LiveSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveSessions", reflect.TypeOf((*MockSessionOps)(nil).LiveSessions))
}

// ParkAndLaunch mocks base method.
func (m *MockSessionOps) ParkAndLaunch(p ops.ParkParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParkAndLaunch", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParkAndLaunch indicates an expected call of ParkAndLaunch.
func (mr *MockSessionOpsMockRecorder) ParkAndLaunch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParkAndLaunch", reflect.TypeOf((*MockSessionOps)(nil).ParkAndLaunch), p)
}

// StopSessions mocks base method.
func (m *MockSessionOps) StopSessions(sessions []claude.Session) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSessions", sessions)
	ret0, _ := ret[0].(int)
	return ret0
}

// StopSessions indicates an expected call of StopSessions.
func (mr *MockSessionOpsMockRecorder) StopSessions(sessions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSessions", reflect.TypeOf((*MockSessionOps)(nil).StopSessions), sessions)
}

// SwitchToWindow mocks base method.
func (m *MockSessionOps) SwitchToWindow(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchToWindow", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchToWindow indicates an expected call of SwitchToWindow.
func (mr *MockSessionOpsMockRecorder) SwitchToWindow(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToWindow", reflect.TypeOf((*MockSessionOps)(nil).SwitchToWindow), target)
}

// WindowExists mocks base method.
func (m *MockSessionOps) WindowExists(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowExists", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WindowExists indicates an expected call of WindowExists.
func (mr *MockSessionOpsMockRecorder) WindowExists(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowExists", reflect.TypeOf((*MockSessionOps)(nil).WindowExists), name)
}
