// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rvanmech/unky-mo/internal/web (interfaces: StateReader,ProjectLister,WorktreeReader,PRClient,TicketSource,PromptSender,SessionHistory,SessionOps,GitFiles,ChangeAnalyzer,ScopeChecker,Terminals,Shells,ClaudePane,Subagents,SlashCommands,Restarter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_deps.go -package=mock_web github.com/rvanmech/unky-mo/internal/web StateReader,ProjectLister,WorktreeReader,PRClient,TicketSource,PromptSender,SessionHistory,SessionOps,GitFiles,ChangeAnalyzer,ScopeChecker,Terminals,Shells,ClaudePane,Subagents,SlashCommands,Restarter
//

// Package mock_web is a generated GoMock package.
package mock_web

import (
	context "context"
	reflect "reflect"

	claude "github.com/rvanmech/unky-mo/internal/claude"
	gitfiles "github.com/rvanmech/unky-mo/internal/gitfiles"
	github "github.com/rvanmech/unky-mo/internal/github"
	ops "github.com/rvanmech/unky-mo/internal/ops"
	project "github.com/rvanmech/unky-mo/internal/project"
	review "github.com/rvanmech/unky-mo/internal/review"
	state "github.com/rvanmech/unky-mo/internal/state"
	tickets "github.com/rvanmech/unky-mo/internal/tickets"
	gomock "go.uber.org/mock/gomock"
)

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockStateReader) Read() (*state.StateFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(*state.StateFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockStateReaderMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockStateReader)(nil).Read))
}

// MockProjectLister is a mock of ProjectLister interface.
type MockProjectLister struct {
	ctrl     *gomock.Controller
	recorder *MockProjectListerMockRecorder
	isgomock struct{}
}

// MockProjectListerMockRecorder is the mock recorder for MockProjectLister.
type MockProjectListerMockRecorder struct {
	mock *MockProjectLister
}

// NewMockProjectLister creates a new mock instance.
func NewMockProjectLister(ctrl *gomock.Controller) *MockProjectLister {
	mock := &MockProjectLister{ctrl: ctrl}
	mock.recorder = &MockProjectListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectLister) EXPECT() *MockProjectListerMockRecorder {
	return m.recorder
}

// LoadProjects mocks base method.
func (m *MockProjectLister) LoadProjects() ([]project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProjects")
	ret0, _ := ret[0].([]project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProjects indicates an expected call of LoadProjects.
func (mr *MockProjectListerMockRecorder) LoadProjects() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProjects", reflect.TypeOf((*MockProjectLister)(nil).LoadProjects))
}

// MockWorktreeReader is a mock of WorktreeReader interface.
type MockWorktreeReader struct {
	ctrl     *gomock.Controller
	recorder *MockWorktreeReaderMockRecorder
	isgomock struct{}
}

// MockWorktreeReaderMockRecorder is the mock recorder for MockWorktreeReader.
type MockWorktreeReaderMockRecorder struct {
	mock *MockWorktreeReader
}

// NewMockWorktreeReader creates a new mock instance.
func NewMockWorktreeReader(ctrl *gomock.Controller) *MockWorktreeReader {
	mock := &MockWorktreeReader{ctrl: ctrl}
	mock.recorder = &MockWorktreeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorktreeReader) EXPECT() *MockWorktreeReaderMockRecorder {
	return m.recorder
}

// ListBranches mocks base method.
func (m *MockWorktreeReader) ListBranches(projectPath string) ([]project.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", projectPath)
	ret0, _ := ret[0].([]project.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockWorktreeReaderMockRecorder) ListBranches(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockWorktreeReader)(nil).ListBranches), projectPath)
}

// MockPRClient is a mock of PRClient interface.
type MockPRClient struct {
	ctrl     *gomock.Controller
	recorder *MockPRClientMockRecorder
	isgomock struct{}
}

// MockPRClientMockRecorder is the mock recorder for MockPRClient.
type MockPRClientMockRecorder struct {
	mock *MockPRClient
}

// NewMockPRClient creates a new mock instance.
func NewMockPRClient(ctrl *gomock.Controller) *MockPRClient {
	mock := &MockPRClient{ctrl: ctrl}
	mock.recorder = &MockPRClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRClient) EXPECT() *MockPRClientMockRecorder {
	return m.recorder
}

// GetPRDetail mocks base method.
func (m *MockPRClient) GetPRDetail(projectPath string, number int) (*github.PRDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRDetail", projectPath, number)
	ret0, _ := ret[0].(*github.PRDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRDetail indicates an expected call of GetPRDetail.
func (mr *MockPRClientMockRecorder) GetPRDetail(projectPath, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRDetail", reflect.TypeOf((*MockPRClient)(nil).GetPRDetail), projectPath, number)
}

// ListPRs mocks base method.
func (m *MockPRClient) ListPRs(projectPath string) ([]github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRs", projectPath)
	ret0, _ := ret[0].([]github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPRs indicates an expected call of ListPRs.
func (mr *MockPRClientMockRecorder) ListPRs(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRs", reflect.TypeOf((*MockPRClient)(nil).ListPRs), projectPath)
}

// MockTicketSource is a mock of TicketSource interface.
type MockTicketSource struct {
	ctrl     *gomock.Controller
	recorder *MockTicketSourceMockRecorder
	isgomock struct{}
}

// MockTicketSourceMockRecorder is the mock recorder for MockTicketSource.
type MockTicketSourceMockRecorder struct {
	mock *MockTicketSource
}

// NewMockTicketSource creates a new mock instance.
func NewMockTicketSource(ctrl *gomock.Controller) *MockTicketSource {
	mock := &MockTicketSource{ctrl: ctrl}
	mock.recorder = &MockTicketSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketSource) EXPECT() *MockTicketSourceMockRecorder {
	return m.recorder
}

// Detail mocks base method.
func (m *MockTicketSource) Detail(ctx context.Context, providerName, id string) (*tickets.TicketDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, providerName, id)
	ret0, _ := ret[0].(*tickets.TicketDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockTicketSourceMockRecorder) Detail(ctx, providerName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTicketSource)(nil).Detail), ctx, providerName, id)
}

// MyTickets mocks base method.
func (m *MockTicketSource) MyTickets(ctx context.Context) ([]tickets.Ticket, []tickets.FetchResult) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MyTickets", ctx)
	ret0, _ := ret[0].([]tickets.Ticket)
	ret1, _ := ret[1].([]tickets.FetchResult)
	return ret0, ret1
}

// MyTickets indicates an expected call of MyTickets.
func (mr *MockTicketSourceMockRecorder) MyTickets(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MyTickets", reflect.TypeOf((*MockTicketSource)(nil).MyTickets), ctx)
}

// MockPromptSender is a mock of PromptSender interface.
type MockPromptSender struct {
	ctrl     *gomock.Controller
	recorder *MockPromptSenderMockRecorder
	isgomock struct{}
}

// MockPromptSenderMockRecorder is the mock recorder for MockPromptSender.
type MockPromptSenderMockRecorder struct {
	mock *MockPromptSender
}

// NewMockPromptSender creates a new mock instance.
func NewMockPromptSender(ctrl *gomock.Controller) *MockPromptSender {
	mock := &MockPromptSender{ctrl: ctrl}
	mock.recorder = &MockPromptSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptSender) EXPECT() *MockPromptSenderMockRecorder {
	return m.recorder
}

// SendLiteralText mocks base method.
func (m *MockPromptSender) SendLiteralText(target, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLiteralText", target, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLiteralText indicates an expected call of SendLiteralText.
func (mr *MockPromptSenderMockRecorder) SendLiteralText(target, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLiteralText", reflect.TypeOf((*MockPromptSender)(nil).SendLiteralText), target, text)
}

// SendPastedText mocks base method.
func (m *MockPromptSender) SendPastedText(target, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPastedText", target, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPastedText indicates an expected call of SendPastedText.
func (mr *MockPromptSenderMockRecorder) SendPastedText(target, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPastedText", reflect.TypeOf((*MockPromptSender)(nil).SendPastedText), target, text)
}

// SendPrompt mocks base method.
func (m *MockPromptSender) SendPrompt(target, text string, imagePaths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPrompt", target, text, imagePaths)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPrompt indicates an expected call of SendPrompt.
func (mr *MockPromptSenderMockRecorder) SendPrompt(target, text, imagePaths any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPrompt", reflect.TypeOf((*MockPromptSender)(nil).SendPrompt), target, text, imagePaths)
}

// MockSessionHistory is a mock of SessionHistory interface.
type MockSessionHistory struct {
	ctrl     *gomock.Controller
	recorder *MockSessionHistoryMockRecorder
	isgomock struct{}
}

// MockSessionHistoryMockRecorder is the mock recorder for MockSessionHistory.
type MockSessionHistoryMockRecorder struct {
	mock *MockSessionHistory
}

// NewMockSessionHistory creates a new mock instance.
func NewMockSessionHistory(ctrl *gomock.Controller) *MockSessionHistory {
	mock := &MockSessionHistory{ctrl: ctrl}
	mock.recorder = &MockSessionHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionHistory) EXPECT() *MockSessionHistoryMockRecorder {
	return m.recorder
}

// ContextTokens mocks base method.
func (m *MockSessionHistory) ContextTokens(path, sessionID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextTokens", path, sessionID)
	ret0, _ := ret[0].(int)
	return ret0
}

// ContextTokens indicates an expected call of ContextTokens.
func (mr *MockSessionHistoryMockRecorder) ContextTokens(path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextTokens", reflect.TypeOf((*MockSessionHistory)(nil).ContextTokens), path, sessionID)
}

// RecentSessions mocks base method.
func (m *MockSessionHistory) RecentSessions(path string, n int) []claude.RecentSession {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentSessions", path, n)
	ret0, _ := ret[0].([]claude.RecentSession)
	return ret0
}

// RecentSessions indicates an expected call of RecentSessions.
func (mr *MockSessionHistoryMockRecorder) RecentSessions(path, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentSessions", reflect.TypeOf((*MockSessionHistory)(nil).RecentSessions), path, n)
}

// TranscriptExists mocks base method.
func (m *MockSessionHistory) TranscriptExists(path, sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscriptExists", path, sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// TranscriptExists indicates an expected call of TranscriptExists.
func (mr *MockSessionHistoryMockRecorder) TranscriptExists(path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscriptExists", reflect.TypeOf((*MockSessionHistory)(nil).TranscriptExists), path, sessionID)
}

// MockSessionOps is a mock of SessionOps interface.
type MockSessionOps struct {
	ctrl     *gomock.Controller
	recorder *MockSessionOpsMockRecorder
	isgomock struct{}
}

// MockSessionOpsMockRecorder is the mock recorder for MockSessionOps.
type MockSessionOpsMockRecorder struct {
	mock *MockSessionOps
}

// NewMockSessionOps creates a new mock instance.
func NewMockSessionOps(ctrl *gomock.Controller) *MockSessionOps {
	mock := &MockSessionOps{ctrl: ctrl}
	mock.recorder = &MockSessionOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionOps) EXPECT() *MockSessionOpsMockRecorder {
	return m.recorder
}

// CleanupWorktree mocks base method.
func (m *MockSessionOps) CleanupWorktree(p ops.CleanupParams) (*ops.CleanupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupWorktree", p)
	ret0, _ := ret[0].(*ops.CleanupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupWorktree indicates an expected call of CleanupWorktree.
func (mr *MockSessionOpsMockRecorder) CleanupWorktree(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupWorktree", reflect.TypeOf((*MockSessionOps)(nil).CleanupWorktree), p)
}

// CreateWorktreeAndLaunch mocks base method.
func (m *MockSessionOps) CreateWorktreeAndLaunch(p ops.WorktreeParams) (*ops.WorktreeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorktreeAndLaunch", p)
	ret0, _ := ret[0].(*ops.WorktreeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorktreeAndLaunch indicates an expected call of CreateWorktreeAndLaunch.
func (mr *MockSessionOpsMockRecorder) CreateWorktreeAndLaunch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorktreeAndLaunch", reflect.TypeOf((*MockSessionOps)(nil).CreateWorktreeAndLaunch), p)
}

// IsDirty mocks base method.
func (m *MockSessionOps) IsDirty(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDirty", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsDirty indicates an expected call of IsDirty.
func (mr *MockSessionOpsMockRecorder) IsDirty(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDirty", reflect.TypeOf((*MockSessionOps)(nil).IsDirty), path)
}

// Launch mocks base method.
func (m *MockSessionOps) Launch(p ops.LaunchParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Launch indicates an expected call of Launch.
func (mr *MockSessionOpsMockRecorder) Launch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockSessionOps)(nil).Launch), p)
}

// LaunchSibling mocks base method.
func (m *MockSessionOps) LaunchSibling(p ops.SiblingParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LaunchSibling", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LaunchSibling indicates an expected call of LaunchSibling.
func (mr *MockSessionOpsMockRecorder) LaunchSibling(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaunchSibling", reflect.TypeOf((*MockSessionOps)(nil).LaunchSibling), p)
}

// LiftSessionToWorktree mocks base method.
func (m *MockSessionOps) LiftSessionToWorktree(p ops.LiftParams) (*ops.LiftResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiftSessionToWorktree", p)
	ret0, _ := ret[0].(*ops.LiftResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiftSessionToWorktree indicates an expected call of LiftSessionToWorktree.
func (mr *MockSessionOpsMockRecorder) LiftSessionToWorktree(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiftSessionToWorktree", reflect.TypeOf((*MockSessionOps)(nil).LiftSessionToWorktree), p)
}

// LiveSessions mocks base method.
func (m *MockSessionOps) LiveSessions() ([]claude.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveSessions")
	ret0, _ := ret[0].([]claude.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LiveSessions indicates an expected call of LiveSessions.
func (mr *MockSessionOpsMockRecorder) LiveSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveSessions", reflect.TypeOf((*MockSessionOps)(nil).LiveSessions))
}

// ParkAndLaunch mocks base method.
func (m *MockSessionOps) ParkAndLaunch(p ops.ParkParams) (*ops.LaunchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParkAndLaunch", p)
	ret0, _ := ret[0].(*ops.LaunchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParkAndLaunch indicates an expected call of ParkAndLaunch.
func (mr *MockSessionOpsMockRecorder) ParkAndLaunch(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParkAndLaunch", reflect.TypeOf((*MockSessionOps)(nil).ParkAndLaunch), p)
}

// StopSessions mocks base method.
func (m *MockSessionOps) StopSessions(sessions []claude.Session) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSessions", sessions)
	ret0, _ := ret[0].(int)
	return ret0
}

// StopSessions indicates an expected call of StopSessions.
func (mr *MockSessionOpsMockRecorder) StopSessions(sessions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSessions", reflect.TypeOf((*MockSessionOps)(nil).StopSessions), sessions)
}

// SwitchToWindow mocks base method.
func (m *MockSessionOps) SwitchToWindow(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchToWindow", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchToWindow indicates an expected call of SwitchToWindow.
func (mr *MockSessionOpsMockRecorder) SwitchToWindow(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToWindow", reflect.TypeOf((*MockSessionOps)(nil).SwitchToWindow), target)
}

// WindowExists mocks base method.
func (m *MockSessionOps) WindowExists(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowExists", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WindowExists indicates an expected call of WindowExists.
func (mr *MockSessionOpsMockRecorder) WindowExists(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowExists", reflect.TypeOf((*MockSessionOps)(nil).WindowExists), name)
}

// MockGitFiles is a mock of GitFiles interface.
type MockGitFiles struct {
	ctrl     *gomock.Controller
	recorder *MockGitFilesMockRecorder
	isgomock struct{}
}

// MockGitFilesMockRecorder is the mock recorder for MockGitFiles.
type MockGitFilesMockRecorder struct {
	mock *MockGitFiles
}

// NewMockGitFiles creates a new mock instance.
func NewMockGitFiles(ctrl *gomock.Controller) *MockGitFiles {
	mock := &MockGitFiles{ctrl: ctrl}
	mock.recorder = &MockGitFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitFiles) EXPECT() *MockGitFilesMockRecorder {
	return m.recorder
}

// Branch mocks base method.
func (m *MockGitFiles) Branch(dir string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Branch", dir)
	ret0, _ := ret[0].(string)
	return ret0
}

// Branch indicates an expected call of Branch.
func (mr *MockGitFilesMockRecorder) Branch(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Branch", reflect.TypeOf((*MockGitFiles)(nil).Branch), dir)
}

// Changes mocks base method.
func (m *MockGitFiles) Changes(dir string) (*gitfiles.Changes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changes", dir)
	ret0, _ := ret[0].(*gitfiles.Changes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Changes indicates an expected call of Changes.
func (mr *MockGitFilesMockRecorder) Changes(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changes", reflect.TypeOf((*MockGitFiles)(nil).Changes), dir)
}

// Commit mocks base method.
func (m *MockGitFiles) Commit(root, hash string) (*gitfiles.CommitDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", root, hash)
	ret0, _ := ret[0].(*gitfiles.CommitDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockGitFilesMockRecorder) Commit(root, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockGitFiles)(nil).Commit), root, hash)
}

// CommitFile mocks base method.
func (m *MockGitFiles) CommitFile(root, hash, path string) (*gitfiles.CommitFileDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitFile", root, hash, path)
	ret0, _ := ret[0].(*gitfiles.CommitFileDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitFile indicates an expected call of CommitFile.
func (mr *MockGitFilesMockRecorder) CommitFile(root, hash, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitFile", reflect.TypeOf((*MockGitFiles)(nil).CommitFile), root, hash, path)
}

// FetchBase mocks base method.
func (m *MockGitFiles) FetchBase(root, base string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchBase", root, base)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchBase indicates an expected call of FetchBase.
func (mr *MockGitFilesMockRecorder) FetchBase(root, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchBase", reflect.TypeOf((*MockGitFiles)(nil).FetchBase), root, base)
}

// Log mocks base method.
func (m *MockGitFiles) Log(dir, scope string) (*gitfiles.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", dir, scope)
	ret0, _ := ret[0].(*gitfiles.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Log indicates an expected call of Log.
func (mr *MockGitFilesMockRecorder) Log(dir, scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockGitFiles)(nil).Log), dir, scope)
}

// Overview mocks base method.
func (m *MockGitFiles) Overview(dir, mode string) (*gitfiles.Overview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Overview", dir, mode)
	ret0, _ := ret[0].(*gitfiles.Overview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Overview indicates an expected call of Overview.
func (mr *MockGitFilesMockRecorder) Overview(dir, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Overview", reflect.TypeOf((*MockGitFiles)(nil).Overview), dir, mode)
}

// OverviewAt mocks base method.
func (m *MockGitFiles) OverviewAt(root, branch, head, base string) (*gitfiles.Overview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverviewAt", root, branch, head, base)
	ret0, _ := ret[0].(*gitfiles.Overview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OverviewAt indicates an expected call of OverviewAt.
func (mr *MockGitFilesMockRecorder) OverviewAt(root, branch, head, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverviewAt", reflect.TypeOf((*MockGitFiles)(nil).OverviewAt), root, branch, head, base)
}

// ReadAt mocks base method.
func (m *MockGitFiles) ReadAt(root, rev, path string) (*gitfiles.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAt", root, rev, path)
	ret0, _ := ret[0].(*gitfiles.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAt indicates an expected call of ReadAt.
func (mr *MockGitFilesMockRecorder) ReadAt(root, rev, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAt", reflect.TypeOf((*MockGitFiles)(nil).ReadAt), root, rev, path)
}

// ReadFile mocks base method.
func (m *MockGitFiles) ReadFile(root, path string) (*gitfiles.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", root, path)
	ret0, _ := ret[0].(*gitfiles.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockGitFilesMockRecorder) ReadFile(root, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockGitFiles)(nil).ReadFile), root, path)
}

// ReadHEAD mocks base method.
func (m *MockGitFiles) ReadHEAD(root, path string) (*gitfiles.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadHEAD", root, path)
	ret0, _ := ret[0].(*gitfiles.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadHEAD indicates an expected call of ReadHEAD.
func (mr *MockGitFilesMockRecorder) ReadHEAD(root, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadHEAD", reflect.TypeOf((*MockGitFiles)(nil).ReadHEAD), root, path)
}

// ResolveBranch mocks base method.
func (m *MockGitFiles) ResolveBranch(root, branch string, remote bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveBranch", root, branch, remote)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveBranch indicates an expected call of ResolveBranch.
func (mr *MockGitFilesMockRecorder) ResolveBranch(root, branch, remote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveBranch", reflect.TypeOf((*MockGitFiles)(nil).ResolveBranch), root, branch, remote)
}

// ResolvePR mocks base method.
func (m *MockGitFiles) ResolvePR(root string, n int, base string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePR", root, n, base)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolvePR indicates an expected call of ResolvePR.
func (mr *MockGitFilesMockRecorder) ResolvePR(root, n, base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePR", reflect.TypeOf((*MockGitFiles)(nil).ResolvePR), root, n, base)
}

// Tree mocks base method.
func (m *MockGitFiles) Tree(dir string) (string, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree", dir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Tree indicates an expected call of Tree.
func (mr *MockGitFilesMockRecorder) Tree(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockGitFiles)(nil).Tree), dir)
}

// TreeAt mocks base method.
func (m *MockGitFiles) TreeAt(root, head string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeAt", root, head)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeAt indicates an expected call of TreeAt.
func (mr *MockGitFilesMockRecorder) TreeAt(root, head any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeAt", reflect.TypeOf((*MockGitFiles)(nil).TreeAt), root, head)
}

// WriteFile mocks base method.
func (m *MockGitFiles) WriteFile(root, path, text, baseHash string) (*gitfiles.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", root, path, text, baseHash)
	ret0, _ := ret[0].(*gitfiles.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockGitFilesMockRecorder) WriteFile(root, path, text, baseHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockGitFiles)(nil).WriteFile), root, path, text, baseHash)
}

// MockChangeAnalyzer is a mock of ChangeAnalyzer interface.
type MockChangeAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockChangeAnalyzerMockRecorder
	isgomock struct{}
}

// MockChangeAnalyzerMockRecorder is the mock recorder for MockChangeAnalyzer.
type MockChangeAnalyzerMockRecorder struct {
	mock *MockChangeAnalyzer
}

// NewMockChangeAnalyzer creates a new mock instance.
func NewMockChangeAnalyzer(ctrl *gomock.Controller) *MockChangeAnalyzer {
	mock := &MockChangeAnalyzer{ctrl: ctrl}
	mock.recorder = &MockChangeAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeAnalyzer) EXPECT() *MockChangeAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockChangeAnalyzer) Analyze(o *gitfiles.Overview) (*review.Analysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", o)
	ret0, _ := ret[0].(*review.Analysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockChangeAnalyzerMockRecorder) Analyze(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockChangeAnalyzer)(nil).Analyze), o)
}

// MockScopeChecker is a mock of ScopeChecker interface.
type MockScopeChecker struct {
	ctrl     *gomock.Controller
	recorder *MockScopeCheckerMockRecorder
	isgomock struct{}
}

// MockScopeCheckerMockRecorder is the mock recorder for MockScopeChecker.
type MockScopeCheckerMockRecorder struct {
	mock *MockScopeChecker
}

// NewMockScopeChecker creates a new mock instance.
func NewMockScopeChecker(ctrl *gomock.Controller) *MockScopeChecker {
	mock := &MockScopeChecker{ctrl: ctrl}
	mock.recorder = &MockScopeCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopeChecker) EXPECT() *MockScopeCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockScopeChecker) Check(req review.ScopeRequest) (*review.ScopeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", req)
	ret0, _ := ret[0].(*review.ScopeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockScopeCheckerMockRecorder) Check(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockScopeChecker)(nil).Check), req)
}

// MockTerminals is a mock of Terminals interface.
type MockTerminals struct {
	ctrl     *gomock.Controller
	recorder *MockTerminalsMockRecorder
	isgomock struct{}
}

// MockTerminalsMockRecorder is the mock recorder for MockTerminals.
type MockTerminalsMockRecorder struct {
	mock *MockTerminals
}

// NewMockTerminals creates a new mock instance.
func NewMockTerminals(ctrl *gomock.Controller) *MockTerminals {
	mock := &MockTerminals{ctrl: ctrl}
	mock.recorder = &MockTerminalsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTerminals) EXPECT() *MockTerminalsMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockTerminals) Capture(paneID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", paneID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockTerminalsMockRecorder) Capture(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockTerminals)(nil).Capture), paneID)
}

// Close mocks base method.
func (m *MockTerminals) Close(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTerminalsMockRecorder) Close(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTerminals)(nil).Close), paneID)
}

// Interrupt mocks base method.
func (m *MockTerminals) Interrupt(paneID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Interrupt", paneID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Interrupt indicates an expected call of Interrupt.
func (mr *MockTerminalsMockRecorder) Interrupt(paneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Interrupt", reflect.TypeOf((*MockTerminals)(nil).Interrupt), paneID)
}

// List mocks base method.
func (m *MockTerminals) List(w state.ProjectState) ([]ops.Terminal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", w)
	ret0, _ := ret[0].([]ops.Terminal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTerminalsMockRecorder) List(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTerminals)(nil).List), w)
}

// New mocks base method.
func (m *MockTerminals) New(w state.ProjectState) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", w)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockTerminalsMockRecorder) New(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockTerminals)(nil).New), w)
}

// SendLine mocks base method.
func (m *MockTerminals) SendLine(paneID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLine", paneID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLine indicates an expected call of SendLine.
func (mr *MockTerminalsMockRecorder) SendLine(paneID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLine", reflect.TypeOf((*MockTerminals)(nil).SendLine), paneID, text)
}

// MockShells is a mock of Shells interface.
type MockShells struct {
	ctrl     *gomock.Controller
	recorder *MockShellsMockRecorder
	isgomock struct{}
}

// MockShellsMockRecorder is the mock recorder for MockShells.
type MockShellsMockRecorder struct {
	mock *MockShells
}

// NewMockShells creates a new mock instance.
func NewMockShells(ctrl *gomock.Controller) *MockShells {
	mock := &MockShells{ctrl: ctrl}
	mock.recorder = &MockShellsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShells) EXPECT() *MockShellsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockShells) List(sessionID string) ([]claude.ActiveShell, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", sessionID)
	ret0, _ := ret[0].([]claude.ActiveShell)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockShellsMockRecorder) List(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockShells)(nil).List), sessionID)
}

// Tail mocks base method.
func (m *MockShells) Tail(path string, maxBytes int) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tail", path, maxBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Tail indicates an expected call of Tail.
func (mr *MockShellsMockRecorder) Tail(path, maxBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*MockShells)(nil).Tail), path, maxBytes)
}

// MockClaudePane is a mock of ClaudePane interface.
type MockClaudePane struct {
	ctrl     *gomock.Controller
	recorder *MockClaudePaneMockRecorder
	isgomock struct{}
}

// MockClaudePaneMockRecorder is the mock recorder for MockClaudePane.
type MockClaudePaneMockRecorder struct {
	mock *MockClaudePane
}

// NewMockClaudePane creates a new mock instance.
func NewMockClaudePane(ctrl *gomock.Controller) *MockClaudePane {
	mock := &MockClaudePane{ctrl: ctrl}
	mock.recorder = &MockClaudePaneMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaudePane) EXPECT() *MockClaudePaneMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockClaudePane) Capture(target string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", target)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockClaudePaneMockRecorder) Capture(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockClaudePane)(nil).Capture), target)
}

// CycleMode mocks base method.
func (m *MockClaudePane) CycleMode(target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CycleMode", target)
	ret0, _ := ret[0].(error)
	return ret0
}

// CycleMode indicates an expected call of CycleMode.
func (mr *MockClaudePaneMockRecorder) CycleMode(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CycleMode", reflect.TypeOf((*MockClaudePane)(nil).CycleMode), target)
}

// MockSubagents is a mock of Subagents interface.
type MockSubagents struct {
	ctrl     *gomock.Controller
	recorder *MockSubagentsMockRecorder
	isgomock struct{}
}

// MockSubagentsMockRecorder is the mock recorder for MockSubagents.
type MockSubagentsMockRecorder struct {
	mock *MockSubagents
}

// NewMockSubagents creates a new mock instance.
func NewMockSubagents(ctrl *gomock.Controller) *MockSubagents {
	mock := &MockSubagents{ctrl: ctrl}
	mock.recorder = &MockSubagentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubagents) EXPECT() *MockSubagentsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSubagents) List(path, sessionID string) ([]claude.Subagent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", path, sessionID)
	ret0, _ := ret[0].([]claude.Subagent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubagentsMockRecorder) List(path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubagents)(nil).List), path, sessionID)
}

// MockSlashCommands is a mock of SlashCommands interface.
type MockSlashCommands struct {
	ctrl     *gomock.Controller
	recorder *MockSlashCommandsMockRecorder
	isgomock struct{}
}

// MockSlashCommandsMockRecorder is the mock recorder for MockSlashCommands.
type MockSlashCommandsMockRecorder struct {
	mock *MockSlashCommands
}

// NewMockSlashCommands creates a new mock instance.
func NewMockSlashCommands(ctrl *gomock.Controller) *MockSlashCommands {
	mock := &MockSlashCommands{ctrl: ctrl}
	mock.recorder = &MockSlashCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlashCommands) EXPECT() *MockSlashCommandsMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockSlashCommands) List(path, sessionID string) []claude.SlashCommand {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", path, sessionID)
	ret0, _ := ret[0].([]claude.SlashCommand)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSlashCommandsMockRecorder) List(path, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSlashCommands)(nil).List), path, sessionID)
}

// MockRestarter is a mock of Restarter interface.
type MockRestarter struct {
	ctrl     *gomock.Controller
	recorder *MockRestarterMockRecorder
	isgomock struct{}
}

// MockRestarterMockRecorder is the mock recorder for MockRestarter.
type MockRestarterMockRecorder struct {
	mock *MockRestarter
}

// NewMockRestarter creates a new mock instance.
func NewMockRestarter(ctrl *gomock.Controller) *MockRestarter {
	mock := &MockRestarter{ctrl: ctrl}
	mock.recorder = &MockRestarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestarter) EXPECT() *MockRestarterMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockRestarter) Restart() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart")
	ret0, _ := ret[0].(error)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockRestarterMockRecorder) Restart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockRestarter)(nil).Restart))
}
